sudo: required
language: node_js

node_js:
- '4.5.0'

env:
  global:
  - GH_REF=github.com/hotosm/oam-catalog.git
  - PRODUCTION_BRANCH=master
  - secure: AhiKIqAYPeXH1HjhYza/VdMJrp8wCri5WNRY+Kdkb4piYEK20dAQPVgcVT2EM1tvlyZL5Q0ZU4rtnATkJOU3k9DQHI99xVjk4MjnqfpkrM9iZtif6o9xDZwf9iWwBeuu9MmKH0tsvKhktxrJkzZ7vAThurZVz89ZPoCAXuudyqk=

services: mongodb

before_install:
- echo "Installing libvips..."
- sudo add-apt-repository -y ppa:lovell/precise-backport-vips
- sudo apt-get update
- sudo apt-get install -y libvips-dev
- echo "Completed libvips installation."
- echo "Installing latest mongodb"
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
- sudo apt-get update && sudo apt-get install -y mongodb-org
- sudo service mongod restart
- echo "Completed installing mongodb"
- echo "Installing gdal-bin"
- sudo apt-get install gdal-bin
- echo "Completed installing gdal-bin"
- chmod +x ./.build_scripts/docs.sh

after_success:
- "./.build_scripts/docs.sh"

deploy:
  provider: heroku
  api_key:
    secure: iZGqyYrx4i7+MPDa0Lopoe/TULu9DNWc2UsYqB8+f39xNhpRNHqIR0lz5VFWl6oQugj0XeZnHpN+f4W+2jfy6ThyTUs42uFAE43HThVipPhf28NdeuCJVje5Qu2ZjMv9spRskalxBrJjdJ8G9C5Vxwx1+LmnjVcyvsk0ycSA38o=
  app: oam-catalog
  on:
    repo: hotosm/oam-catalog
    branch: master
